# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cqql/projects/tum-graph-analytics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cqql/projects/tum-graph-analytics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cqql/projects/tum-graph-analytics/CMakeFiles /home/cqql/projects/tum-graph-analytics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cqql/projects/tum-graph-analytics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named petuum_bosen

# Build rule for target.
petuum_bosen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 petuum_bosen
.PHONY : petuum_bosen

# fast build rule for target.
petuum_bosen/fast:
	$(MAKE) -f libs/bosen/src/CMakeFiles/petuum_bosen.dir/build.make libs/bosen/src/CMakeFiles/petuum_bosen.dir/build
.PHONY : petuum_bosen/fast

#=============================================================================
# Target rules for targets named dml_main

# Build rule for target.
dml_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dml_main
.PHONY : dml_main

# fast build rule for target.
dml_main/fast:
	$(MAKE) -f libs/bosen/app/dml/CMakeFiles/dml_main.dir/build.make libs/bosen/app/dml/CMakeFiles/dml_main.dir/build
.PHONY : dml_main/fast

#=============================================================================
# Target rules for targets named dnn_predict_main

# Build rule for target.
dnn_predict_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dnn_predict_main
.PHONY : dnn_predict_main

# fast build rule for target.
dnn_predict_main/fast:
	$(MAKE) -f libs/bosen/app/dnn/CMakeFiles/dnn_predict_main.dir/build.make libs/bosen/app/dnn/CMakeFiles/dnn_predict_main.dir/build
.PHONY : dnn_predict_main/fast

#=============================================================================
# Target rules for targets named dnn_main

# Build rule for target.
dnn_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dnn_main
.PHONY : dnn_main

# fast build rule for target.
dnn_main/fast:
	$(MAKE) -f libs/bosen/app/dnn/CMakeFiles/dnn_main.dir/build.make libs/bosen/app/dnn/CMakeFiles/dnn_main.dir/build
.PHONY : dnn_main/fast

#=============================================================================
# Target rules for targets named dnn_gendata_main

# Build rule for target.
dnn_gendata_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dnn_gendata_main
.PHONY : dnn_gendata_main

# fast build rule for target.
dnn_gendata_main/fast:
	$(MAKE) -f libs/bosen/app/dnn/CMakeFiles/dnn_gendata_main.dir/build.make libs/bosen/app/dnn/CMakeFiles/dnn_gendata_main.dir/build
.PHONY : dnn_gendata_main/fast

#=============================================================================
# Target rules for targets named dnn_speech_gendata_main

# Build rule for target.
dnn_speech_gendata_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dnn_speech_gendata_main
.PHONY : dnn_speech_gendata_main

# fast build rule for target.
dnn_speech_gendata_main/fast:
	$(MAKE) -f libs/bosen/app/dnn_speech/CMakeFiles/dnn_speech_gendata_main.dir/build.make libs/bosen/app/dnn_speech/CMakeFiles/dnn_speech_gendata_main.dir/build
.PHONY : dnn_speech_gendata_main/fast

#=============================================================================
# Target rules for targets named dnn_speech_main

# Build rule for target.
dnn_speech_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dnn_speech_main
.PHONY : dnn_speech_main

# fast build rule for target.
dnn_speech_main/fast:
	$(MAKE) -f libs/bosen/app/dnn_speech/CMakeFiles/dnn_speech_main.dir/build.make libs/bosen/app/dnn_speech/CMakeFiles/dnn_speech_main.dir/build
.PHONY : dnn_speech_main/fast

#=============================================================================
# Target rules for targets named kmeans_main

# Build rule for target.
kmeans_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kmeans_main
.PHONY : kmeans_main

# fast build rule for target.
kmeans_main/fast:
	$(MAKE) -f libs/bosen/app/kmeans/CMakeFiles/kmeans_main.dir/build.make libs/bosen/app/kmeans/CMakeFiles/kmeans_main.dir/build
.PHONY : kmeans_main/fast

#=============================================================================
# Target rules for targets named mlr_gendata_main

# Build rule for target.
mlr_gendata_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlr_gendata_main
.PHONY : mlr_gendata_main

# fast build rule for target.
mlr_gendata_main/fast:
	$(MAKE) -f libs/bosen/app/mlr/CMakeFiles/mlr_gendata_main.dir/build.make libs/bosen/app/mlr/CMakeFiles/mlr_gendata_main.dir/build
.PHONY : mlr_gendata_main/fast

#=============================================================================
# Target rules for targets named mlr_main

# Build rule for target.
mlr_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlr_main
.PHONY : mlr_main

# fast build rule for target.
mlr_main/fast:
	$(MAKE) -f libs/bosen/app/mlr/CMakeFiles/mlr_main.dir/build.make libs/bosen/app/mlr/CMakeFiles/mlr_main.dir/build
.PHONY : mlr_main/fast

#=============================================================================
# Target rules for targets named nmf_main

# Build rule for target.
nmf_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nmf_main
.PHONY : nmf_main

# fast build rule for target.
nmf_main/fast:
	$(MAKE) -f libs/bosen/app/NMF/CMakeFiles/nmf_main.dir/build.make libs/bosen/app/NMF/CMakeFiles/nmf_main.dir/build
.PHONY : nmf_main/fast

#=============================================================================
# Target rules for targets named rand_forest_main

# Build rule for target.
rand_forest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rand_forest_main
.PHONY : rand_forest_main

# fast build rule for target.
rand_forest_main/fast:
	$(MAKE) -f libs/bosen/app/rand_forest/CMakeFiles/rand_forest_main.dir/build.make libs/bosen/app/rand_forest/CMakeFiles/rand_forest_main.dir/build
.PHONY : rand_forest_main/fast

#=============================================================================
# Target rules for targets named sparsecoding_main

# Build rule for target.
sparsecoding_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sparsecoding_main
.PHONY : sparsecoding_main

# fast build rule for target.
sparsecoding_main/fast:
	$(MAKE) -f libs/bosen/app/sparsecoding/CMakeFiles/sparsecoding_main.dir/build.make libs/bosen/app/sparsecoding/CMakeFiles/sparsecoding_main.dir/build
.PHONY : sparsecoding_main/fast

#=============================================================================
# Target rules for targets named mf-als

# Build rule for target.
mf-als: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mf-als
.PHONY : mf-als

# fast build rule for target.
mf-als/fast:
	$(MAKE) -f mf-als/CMakeFiles/mf-als.dir/build.make mf-als/CMakeFiles/mf-als.dir/build
.PHONY : mf-als/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... petuum_bosen"
	@echo "... dml_main"
	@echo "... dnn_predict_main"
	@echo "... dnn_main"
	@echo "... dnn_gendata_main"
	@echo "... dnn_speech_gendata_main"
	@echo "... dnn_speech_main"
	@echo "... kmeans_main"
	@echo "... mlr_gendata_main"
	@echo "... mlr_main"
	@echo "... nmf_main"
	@echo "... rand_forest_main"
	@echo "... sparsecoding_main"
	@echo "... mf-als"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

