#!/usr/bin/env python

import argparse
import csv
import json
import os
import sys


def extract(fin, fout):
    writer = csv.writer(fout)

    for line in fin:
        item = json.loads(line)
        writer.writerow([item["reviewerID"], item["asin"], item["overall"],
                         item["unixReviewTime"]])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--file", help="Reviews file")

    args = parser.parse_args()

    if args.file:
        csv_file = os.path.splitext(args.file)[0] + ".csv"

        with open(args.file, "r") as fin:
            with open(csv_file, "w") as fout:
                extract(fin, fout)
    else:
        extract(sys.stdin, sys.stdout)


if __name__ == "__main__":
    main()
