#!/usr/bin/env python

import argparse
import csv
import json
import os


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("reviews", help="Reviews file")

    args = parser.parse_args()
    items = []

    with open(args.reviews, "r") as f:
        for line in f:
            item = json.loads(line)
            items.append([item["reviewerID"], item["asin"], item["overall"],
                          item["unixReviewTime"]])

    csv_file = os.path.splitext(args.reviews)[0] + ".csv"
    with open(csv_file, "w") as f:
        writer = csv.writer(f)
        writer.writerows(items)


if __name__ == "__main__":
    main()
