#!/usr/bin/env python

import argparse

import numpy as np


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("file", help="CSV matrix file to transpose")

    args = parser.parse_args()

    A = np.loadtxt(args.file, delimiter=",")
    np.savetxt(args.file, A.T, delimiter=",")


if __name__ == "__main__":
    main()
